# MYSQL SETTINGS
development:
    adapter: mysql
    database: simpleblog
    username: root
    password: 
    encoding: utf8
    host: localhost
    pool: 2
    timeout: 5000

production:
    adapter: mysql
    database: 
    username: 
    password: 
    encoding: utf8
    host: localhost
    pool: 2
    timeout: 5000