development:
    :action_controller:
        :session:
          :secret:  
    :cache:
        :name: "simpleblog"
        :timeout: 15.minutes
    :site:
        :name: ""
        :tagline: ""
        :description: ""
        :keywords: ""
        :host: "www.domain.com"
        :locale: 'en'
        :noreply: 'noreply@domain.com'
        :email: 'sender@domain.com'
        :salt: ""
        :info_account_user_name: '(make sure you get this username :-))'
    :s3:
        :bucket: "simpleblog-dev"
    :recaptcha:
        :public: ""
        :private: ""
    :hoptoad: ""
    :social:
        :share_this: "(optional)"
        :feedburner: "(optional)"
        :facebook_widget_id: "(optional)"
        :subscribe:
            :facebook: "(optional)"
            :twitter: "(optional)"
            :blogtalkradio: "(optional)"
            :youtube: "(optional)"
            :itunes: "(optional)"
            :flickr: "(optional)"
    :google:
        :verification: "(optional, but strongly suggested)"
        :analytics: "(optional)"
    :bitly:
        :login: "(optional but needed for automatic feed updates to Facebook or Twitter)"
        :api_key: "(optional but needed for automatic feed updates to Facebook and login)"
    :twitter:
        :key: "(optional for automatic feed updates to Twitter)"
        :secret: "(optional for automatic feed updates to Twitter)"
        :callback_url: "http://domain.com/account/twitter_account/callback"
    :facebook:
        :key: "(optional for automatic feed updates to Facebook and login)"
        :secret: "(optional for automatic feed updates to Facebook and login)"
        :callback_url: "http://domain.com/account/facebook_account/callback"
    :calais: "(optional for tag suggestion support)"
    :email:
        :host: "(optional for email posting)"
        :port: "(optional for email posting)"
        :username: "(optional for email posting)"
        :password: "(optional for email posting)"
        :service_url: "http://domain.com/admin/incoming"